
image: Visual Studio 2017

configuration:
  - Release
  - Debug

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017"
      platform:
        - x86
    - GENERATOR: "Visual Studio 15 2017 Win64"
      platform:
        - x64
       
#install:
#  - git submodule update --init --recursive

before_build:
  - ps: mkdir build
  - ps: cd build
  - cmake -G%GENERATOR% ..
 
build:
  project: $(APPVEYOR_BUILD_FOLDER)\$(APPVEYOR_PROJECT_NAME).sln
        
        