
image: 
  - Visual Studio 2017

platform:
  - x64
  
install:
  - ps: echo "Downloading conan"
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - ps: python.exe -m pip install --upgrade pip
  - ps: pip.exe install conan
  - ps: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - ps: conan user
  - ps: conan --version

environment:
  matrix:
    - BUILD_SHARED_LIBS: "True"
      CONFIGURATION: "Release"
      RUNTIME: "MD"
    - BUILD_SHARED_LIBS: "False"
      CONFIGURATION: "Release"
      RUNTIME: "MT"
    - BUILD_SHARED_LIBS: "True"
      CONFIGURATION: "Debug"
      RUNTIME: "MDd"
    - BUILD_SHARED_LIBS: "False"
      CONFIGURATION: "Debug"
      RUNTIME: "MTd"

build_script:
  # build gtest from source to avoid linker errors 
  - cmd: conan install glad/0.1.24@bincrafters/stable -o shared=%BUILD_SHARED_LIBS% -s build_type=%CONFIGURATION% -s compiler.runtime=%RUNTIME% --build
  - cmd: mkdir build
  - cmd: conan install . -if build -o build_samples=True -o shared=%BUILD_SHARED_LIBS% -o build_tests=True -s build_type=%CONFIGURATION% -s compiler.runtime=%RUNTIME% --build missing
  - cmd: cd build
  - cmd: conan build ..
  
test_script:
    - ctest -C "%CONFIGURATION%"
    - conan export . qeng/0.0.1@squiregames/testing
    - conan test test_package qeng/0.0.1@squiregames/testing
    