
image: 
  - Visual Studio 2017

platform:
  - x64
  
configuration:
  - Release
  - Debug
  
install:
  - ps: echo "Downloading conan"
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - ps: pip.exe install conan
  - ps: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - ps: conan user
  - ps: conan --version

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      BUILD_SHARED_LIBS: "True"
    - GENERATOR: "Visual Studio 15 2017 Win64"
      BUILD_SHARED_LIBS: "False"

build_script:
  - ps: mkdir build
  - ps: conan install . -if build -o build_samples=True -o shared=$env:BUILD_SHARED_LIBS -o build_tests=$env:BUILD_SHARED_LIBS -s build_type=$env:CONFIGURATION --build missing
  - ps: cd build
  - ps: conan build ..
  
test_script:
    - ctest -C "%CONFIGURATION%"
    