
image: 
  - Visual Studio 2017

platform:
  - x64
  
install:
  - ps: echo "Downloading conan"
  - cmd: set PATH=%PATH%;C:\Python37\Scripts;C:\Python37
  - ps: C:\\Python37\\python.exe -m pip install --upgrade pip
  - ps: C:\\Python37\\Scripts\\pip.exe install conan --no-warn-script-location
  - ps: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - ps: conan user
  - ps: conan --version

environment:
  matrix:
    - BUILD_SHARED_LIBS: "True"
      CONFIGURATION: "Release"
      RUNTIME: "MD"
    - BUILD_SHARED_LIBS: "False"
      CONFIGURATION: "Release"
      RUNTIME: "MT"
    - BUILD_SHARED_LIBS: "True"
      CONFIGURATION: "Debug"
      RUNTIME: "MDd"
    - BUILD_SHARED_LIBS: "False"
      CONFIGURATION: "Debug"
      RUNTIME: "MTd"

build_script:
  # build gtest from source to avoid linker errors 
  - cmd: conan install gtest/1.8.0@bincrafters/stable -o shared=%BUILD_SHARED_LIBS% -s build_type=%CONFIGURATION% -s compiler.runtime=%RUNTIME% --build
  - cmd: mkdir build
  - cmd: conan install . -if build -o build_samples=True -o shared=%BUILD_SHARED_LIBS% -o build_tests=True -s build_type=%CONFIGURATION% -s compiler.runtime=%RUNTIME% -o glad:profile=core -o glad:api_version=3.3 --build missing
  - cmd: cd build
  - cmd: conan build ..
  
test_script:
  - ctest -C "%CONFIGURATION%"
  - cmd: cd ..
  - conan export-pkg . qeng/0.0.1@squiregames/testing -o *:shared=%BUILD_SHARED_LIBS% -s build_type=%CONFIGURATION% -s compiler.runtime=%RUNTIME%
  - conan test test_package qeng/0.0.1@squiregames/testing -o *:shared=%BUILD_SHARED_LIBS% -s build_type=%CONFIGURATION% -s compiler.runtime=%RUNTIME% --build missing
  