
image: 
  - Visual Studio 2017

platform:
  - x64
  
configuration:
  - Release
  - Debug
  
install:
  - ps: echo "Downloading conan"
  - cmmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - ps: pip.exe install conan
  - ps: conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - ps: conan user
  - ps: conan --version

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      BUILD_SHARED_LIBS: "ON"
    - GENERATOR: "Visual Studio 15 2017 Win64"
      BUILD_SHARED_LIBS: "OFF"

build_script:
  - ps: mkdir build
  - ps: conan install . -if build -o build_samples=True -o "shared=%BUILD_SHARED_LIBS%" -o build_tests=True -s "build_type=%CONFIGURATION%"
  - ps: cd build
  - cmake "-G%GENERATOR%" "-DCMAKE_BUILD_TYPE=%CONFIGURATION%" "-DBUILD_SHARED_LIBS=%BUILD_SHARED_LIBS%" -DQENG_BUILD_TESTS=ON -DQENG_BUILD_SAMPLES=ON ..
  - cmake --build . --config "%CONFIGURATION%"
  
test_script:
    - ctest -C "%CONFIGURATION%"
    