
sudo: required
dist: trusty

language: cpp

env:
  global:
    - CMAKECOMPILER=g++-6
  matrix:
    - BUILD_SHARED_LIBS=ON SDL_SHARED=ON SDL_STATIC=OFF
    - BUILD_SHARED_LIBS=OFF SDL_SHARED=OFF SDL_STATIC=ON
  
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
    - os: osx
      script:
        - mkdir build
        - cd build
        - cmake -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS -DSDL_SHARED=$SDL_SHARED -DSDL_STATIC=$SDL_STATIC .. && cmake --build .

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$CMAKECOMPILER -DBUILD_SHARED_LIBS=$BUILD_SHARED_LIBS -DSDL_SHARED=$SDL_SHARED -DSDL_STATIC=$SDL_STATIC .. && cmake --build .
  