
sudo: required
dist: trusty

language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - cmake
      env: COMPILER=g++-6
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
          packages:
            - clang-3.8
            - cmake
      env: COMPILER=clang++-3.8
    - os: osx
      script:
        - mkdir build
        - cd build
        - cmake .. && cmake --build .

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && cmake --build .
  