
sudo: required
dist: trusty

language: cpp
  
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade gcc || brew install gcc || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite gcc || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo python --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo -H pip install --ignore-installed matplotlib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo -H pip install --ignore-installed pyOpenSSL; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo pip install --upgrade cmake; fi
  - sudo pip install conan
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan user
  - conan --version
  
script:
 - mkdir build
 - sudo conan install . -if build -o build_samples=True -o build_tests=True -o shared=$BUILD_SHARED_LIBS -s build_type=$CONFIG --build missing
 - cd build
 - sudo conan build ..
 - ctest -C "%CONFIGURATION%"
 - cd ..
 - sudo conan export-pkg . qeng/0.0.1@squiregames/testing --build-folder build
 - sudo conan test test_package qeng/0.0.1@squiregames/testing -o qeng:shared=$BUILD_SHARED_LIBS -s qeng:build_type=$CONFIG --build missing
  
matrix:
  include:
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-6
           - cmake
           - cmake-data
           - python3
           - python3-pip
     env: COMPILER=g++-6 BUILD_SHARED_LIBS=True CONFIG=Debug
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-6
           - cmake
           - cmake-data
           - python3
           - python3-pip
     env: COMPILER=g++-6 BUILD_SHARED_LIBS=True CONFIG=Release
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-6
           - cmake
           - cmake-data
           - python3
           - python3-pip
     env: COMPILER=g++-6 BUILD_SHARED_LIBS=False CONFIG=Debug
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - g++-6
           - cmake
           - cmake-data
           - python3
           - python3-pip
     env: COMPILER=g++-6 BUILD_SHARED_LIBS=False CONFIG=Release
   - os: osx
     env: BUILD_SHARED_LIBS=True CONFIG=Debug
   - os: osx
     env: BUILD_SHARED_LIBS=True CONFIG=Release
   - os: osx
     env: BUILD_SHARED_LIBS=False CONFIG=Debug
   - os: osx
     env: BUILD_SHARED_LIBS=False CONFIG=Release
     