sudo: required
dist: xenial # TODO upgrade to bionic when Travis CI supports it

language: cpp
  
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade gcc || brew install gcc || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite gcc || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo python3 --version; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo python3; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo -H pip3 install --ignore-installed matplotlib; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo -H pip3 install --ignore-installed pyOpenSSL; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo pip3 install --ignore-installed conan; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo python3 get-pip.py; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 70 --slave /usr/bin/g++ g++ /usr/bin/g++-8; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo python3 -m pip install --upgrade cmake; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo python3 -m pip install --ignore-installed conan; fi
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
  - conan user
  - conan --version
  
script:
 - mkdir build
 - sudo conan install . -if build -o build_samples=True -o build_tests=True -o shared=$BUILD_SHARED_LIBS -s build_type=$CONFIG --build missing
 - cd build
 - sudo conan build ..
 - ctest -C "%CONFIGURATION%"
 - cd ..
 - sudo conan export-pkg . qeng/0.0.1@squiregames/testing --build-folder build
 - sudo conan test test_package qeng/0.0.1@squiregames/testing -o qeng:shared=$BUILD_SHARED_LIBS -s qeng:build_type=$CONFIG --build missing
  
matrix:
  include:
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - gcc-8
           - g++-8
           - cmake
           - cmake-data
           - python3
     env: CC=gcc-8 CXX=g++-8 COMPILER=g++-8 BUILD_SHARED_LIBS=True CONFIG=Debug 
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - gcc-8
           - g++-8
           - cmake
           - cmake-data
           - python3
     env: CC=gcc-8 CXX=g++-8 COMPILER=g++-8 BUILD_SHARED_LIBS=True CONFIG=Release
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - gcc-8
           - g++-8
           - cmake
           - cmake-data
           - python3
     env: CC=gcc-8 CXX=g++-8 COMPILER=g++-8 BUILD_SHARED_LIBS=False CONFIG=Debug
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - gcc-8
           - g++-8
           - cmake
           - cmake-data
           - python3
     env: CC=gcc-8 CXX=g++-8 COMPILER=g++-8 BUILD_SHARED_LIBS=False CONFIG=Release
   - os: osx
     env: BUILD_SHARED_LIBS=True CONFIG=Debug
   - os: osx
     env: BUILD_SHARED_LIBS=True CONFIG=Release
   - os: osx
     env: BUILD_SHARED_LIBS=False CONFIG=Debug
   - os: osx
     env: BUILD_SHARED_LIBS=False CONFIG=Release
  allow_failures: # TODO remove when Travis CI supports bionic in order link glibc2.27
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - gcc-8
           - g++-8
           - cmake
           - cmake-data
           - python3
     env: CC=gcc-8 CXX=g++-8 COMPILER=g++-8 BUILD_SHARED_LIBS=True CONFIG=Debug 
   - os: linux
     compiler: gcc
     addons:
        apt:
          sources:
           - ubuntu-toolchain-r-test
          packages:
           - gcc-8
           - g++-8
           - cmake
           - cmake-data
           - python3
     env: CC=gcc-8 CXX=g++-8 COMPILER=g++-8 BUILD_SHARED_LIBS=True CONFIG=Release
     